// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmyZPQNv_K4SPpx20fLMwbc7QzN3XupDw',
    appId: '1:479776814347:web:9e31b1408be5c8dcb61e0e',
    messagingSenderId: '479776814347',
    projectId: 'corruption-watch-5cef9',
    authDomain: 'corruption-watch-5cef9.firebaseapp.com',
    storageBucket: 'corruption-watch-5cef9.appspot.com',
    measurementId: 'G-CEBZFBGP5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGk3xGojQB3eeAWBpLju_Of5F4L6qCemY',
    appId: '1:479776814347:android:1513ad691bd0182ab61e0e',
    messagingSenderId: '479776814347',
    projectId: 'corruption-watch-5cef9',
    storageBucket: 'corruption-watch-5cef9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQFkFiVBlOgUUOOU-GoHjXzJUgTGwGY1Y',
    appId: '1:479776814347:ios:31143c8cc696206fb61e0e',
    messagingSenderId: '479776814347',
    projectId: 'corruption-watch-5cef9',
    storageBucket: 'corruption-watch-5cef9.appspot.com',
    iosBundleId: 'com.example.corruptionWatch',
  );
}
